### PR TITLE
feat: make the video in song editor draggable, resizable & snappable

### LINKED ISSUE #32: 可拖拽可調整大小的 Player
理論上設想的情況是在桌面 layout 下，player 的位置和大小都可以調整（可磁吸式保持貼邊），由此可以輕易讓出更多空間給歌詞，或是調換影片和歌詞的位置等

### PR DESCRIPTION
**Pull request by oliver139**
Fix #32

[vue3-moveable](https://github.com/daybrush/moveable/tree/master/packages/vue3-moveable) is used
- [x] Draggable
- [x] Resizable
- [x] Snappable to window edge
- [x] Re-position on window resize
- [x] Reset to initial size and location by double clicking the drag handle

Not tested on mobile device yet

### CODE REVIEW

**Review by LittleSound — COMMENTED** [review]
looks good to me. but I think the video window should be fixed when scrolling?

**Comment by oliver139** [comment]
> looks good to me. but I think the video window should be fixed when scrolling?

Oh yes, you are right :D
should use a `position: fixed` here
Let me amend this later

**Comment by oliver139** [comment]
Ok, fixed with some more extra bug:
- [x] The video window is now fixed when scrolling
- [x] `max-width` & `max-height` are now applied to avoid the video being larger then the browser window
- [x] Avoid the video be placed outside the browser window when resetting with double clicking the drag handle

**Review by LittleSound — APPROVED** [review]
LGTM

**Pull request merged**
